import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Youtube } from "lucide-react";
import type { TopicLectureOutput } from "@/ai/flows/topic-lecture-flow";

interface LectureDisplayProps {
  lecture: TopicLectureOutput;
  topic: string;
}

// Basic markdown to HTML (very simplified)
function renderMarkdown(markdown: string) {
  // Replace newlines with <br> for simple paragraph breaks
  // In a real app, use a library like 'marked' or 'react-markdown'
  const html = markdown
    .split('\n\n') // Split by double newlines for paragraphs
    .map(paragraph => `<p class="mb-4">${paragraph.replace(/\n/g, '<br />')}</p>`)
    .join('');
  return { __html: html };
}


export function LectureDisplay({ lecture, topic }: LectureDisplayProps) {
  return (
    <Card className="mt-8">
      <CardHeader>
        <CardTitle className="font-headline text-2xl">Lecture: {topic}</CardTitle>
        <CardDescription>Generated by EduVoice AI</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <h3 className="font-headline text-xl font-semibold mb-2 text-primary">Summary</h3>
          <div className="prose prose-sm max-w-none text-foreground" dangerouslySetInnerHTML={renderMarkdown(lecture.summary)} />
        </div>
        <Separator />
        <div>
          <h3 className="font-headline text-xl font-semibold mb-2 text-primary">Lecture Content</h3>
          <div className="prose prose-sm max-w-none text-foreground" dangerouslySetInnerHTML={renderMarkdown(lecture.lectureContent)} />
        </div>
        {lecture.youtubeVideoLinks && lecture.youtubeVideoLinks.length > 0 && (
          <>
            <Separator />
            <div>
              <h3 className="font-headline text-xl font-semibold mb-3 text-primary">Relevant YouTube Videos</h3>
              <ul className="space-y-3">
                {lecture.youtubeVideoLinks.map((link, index) => {
                  // Attempt to extract video ID for embedding
                  let videoId = null;
                  try {
                    const url = new URL(link);
                    if (url.hostname === "www.youtube.com" || url.hostname === "youtube.com") {
                      videoId = url.searchParams.get("v");
                    } else if (url.hostname === "youtu.be") {
                      videoId = url.pathname.substring(1);
                    }
                  } catch (e) { console.error("Invalid URL:", link); }

                  return (
                    <li key={index} className="group">
                      {videoId ? (
                        <div className="aspect-video rounded-lg overflow-hidden border">
                          <iframe
                            width="100%"
                            height="100%"
                            src={`https://www.youtube.com/embed/${videoId}`}
                            title={`YouTube video player for ${topic}`}
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowFullScreen
                          ></iframe>
                        </div>
                      ) : (
                         <a
                          href={link}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-accent hover:underline flex items-center"
                        >
                          <Youtube className="mr-2 h-5 w-5" /> Watch Video {index + 1}
                        </a>
                      )}
                    </li>
                  );
                })}
              </ul>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}
