
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Youtube } from "lucide-react";
import type { TopicLectureOutput } from "@/ai/flows/topic-lecture-flow";

interface LectureDisplayProps {
  lecture: TopicLectureOutput;
  topic: string;
}

// Basic markdown to HTML (very simplified)
function renderMarkdown(markdown: string) {
  // Replace newlines with <br> for simple paragraph breaks
  // In a real app, use a library like 'marked' or 'react-markdown'
  const html = markdown
    .split('\n\n') // Split by double newlines for paragraphs
    .map(paragraph => `<p class="mb-4">${paragraph.replace(/\n/g, '<br />')}</p>`)
    .join('');
  return { __html: html };
}

function getYouTubeVideoId(url: string): string | null {
  if (!url) return null;
  // Regex to extract video ID from various YouTube URL formats
  // Handles:
  // - https://www.youtube.com/watch?v=VIDEO_ID
  // - https://youtu.be/VIDEO_ID
  // - https://www.youtube.com/embed/VIDEO_ID
  // - https://www.youtube.com/v/VIDEO_ID
  // - https://www.youtube.com/user/channelname#p/a/u/1/VIDEO_ID
  // - https://music.youtube.com/watch?v=VIDEO_ID
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
  const match = url.match(regExp);
  if (match && match[2] && match[2].length === 11) {
    return match[2];
  }
  // Fallback: if the provided link is already just an 11-character ID
  if (url.length === 11 && /^[a-zA-Z0-9_-]+$/.test(url)) {
    return url;
  }
  return null;
}


export function LectureDisplay({ lecture, topic }: LectureDisplayProps) {
  return (
    <Card className="mt-8">
      <CardHeader>
        <CardTitle className="font-headline text-2xl">Lecture: {topic}</CardTitle>
        <CardDescription>Generated by EduVoice AI</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <h3 className="font-headline text-xl font-semibold mb-2 text-primary">Summary</h3>
          <div className="prose prose-sm max-w-none text-foreground" dangerouslySetInnerHTML={renderMarkdown(lecture.summary)} />
        </div>
        <Separator />
        <div>
          <h3 className="font-headline text-xl font-semibold mb-2 text-primary">Lecture Content</h3>
          <div className="prose prose-sm max-w-none text-foreground" dangerouslySetInnerHTML={renderMarkdown(lecture.lectureContent)} />
        </div>
        {lecture.youtubeVideoLinks && lecture.youtubeVideoLinks.length > 0 && (
          <>
            <Separator />
            <div>
              <h3 className="font-headline text-xl font-semibold mb-3 text-primary">Relevant YouTube Videos</h3>
              <ul className="space-y-3">
                {lecture.youtubeVideoLinks.map((link, index) => {
                  const videoId = getYouTubeVideoId(link);

                  return (
                    <li key={index} className="group">
                      {videoId ? (
                        <div className="aspect-video rounded-lg overflow-hidden border">
                          <iframe
                            width="100%"
                            height="100%"
                            src={`https://www.youtube.com/embed/${videoId}`}
                            title={`YouTube video player for ${topic} - Video ${index + 1}`}
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                            allowFullScreen
                          ></iframe>
                        </div>
                      ) : (
                         <a
                          href={link}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-accent hover:underline flex items-center"
                        >
                          <Youtube className="mr-2 h-5 w-5" /> Watch Video {index + 1} (Link)
                        </a>
                      )}
                    </li>
                  );
                })}
              </ul>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}

